//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDA_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbenica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbenica()
        {
            this.Stavka_narudzenice = new HashSet<Stavka_narudzenice>();
        }
    
        public int Narudzbenica_ID { get; set; }
        public int Zaposleni_ID { get; set; }
        public int Kompanija_ID { get; set; }
        public Nullable<int> Broj_narudzbenice { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual Kompanija Kompanija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_narudzenice> Stavka_narudzenice { get; set; }
        public virtual Zaposleni Zaposleni { get; set; }
    }
}
