//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDA_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TV_kuca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TV_kuca()
        {
            this.Kanali = new HashSet<Kanali>();
        }
    
        public int TV_kuca_ID { get; set; }
        public int Struktura_vlasnistva_ID { get; set; }
        public string Naziv { get; set; }
        public string Sediste { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kanali> Kanali { get; set; }
        public virtual Struktura_vlasnistva Struktura_vlasnistva { get; set; }
    }
}
