//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDA_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Dim_Odbor
    {
        public int Odbor_ID { get; set; }
        public string Odbor { get; set; }
        public string Politicka_stranka { get; set; }
        public string Opstina_stranke { get; set; }
    }
}
