//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDA_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zaposleni()
        {
            this.Narudzbenica = new HashSet<Narudzbenica>();
            this.Zaposleni1 = new HashSet<Zaposleni>();
        }
    
        public int Zaposleni_ID { get; set; }
        public int Poz_zaposlenog_ID { get; set; }
        public int Agencija_ID { get; set; }
        public Nullable<int> Nadredjeni_ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string JMBG { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
    
        public virtual Agencija Agencija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzbenica> Narudzbenica { get; set; }
        public virtual Pozicija_zaposlenog Pozicija_zaposlenog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaposleni> Zaposleni1 { get; set; }
        public virtual Zaposleni Zaposleni2 { get; set; }
    }
}
